language: java
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_SDKS=sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a SKIN=WXGA800 LINT=true
  global:
    - TERM=dumb
    - secure: A5Bq4mDhsHqKK8PlxNlxVGJuSBi1L2uBg817821AOXyPjSSXS5GQK+4bIp+io8R/bPzxCNuC8nqJUvupa0GrEgKhzfA0JF5nhMjLyZ5cfpbNOYWCJHlbiZCDkW4MFhtWTCGedu3sQ8WifyJ25ceh+1nxxAn/hIhJUfYssNw1+8Q=

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - export COMPONENTS=extra-android-m2repository,build-tools-19.0.3,android-19,$ANDROID_SDKS
  - curl -3L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

  # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin $SKIN
  #- emulator -avd test -no-audio -no-window &

before_script:
  # Make sure the emulator has started before running tests
  #- wait_for_emulator

install:
 - true

script:
  - sudo chmod +x gradlew
  #- ./gradlew connectedCheck

  - if [[ $LINT == 'true' ]]; then ./gradlew lint ; fi

after_success:
  - ./gradlew uploadArchives -PnexusUsername="${nexusUsername}" -PnexusPassword="${nexusPassword}"

notifications:
  email: false
